[package]
name = "shikisha-term-ai"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "Shikisha-Term-AI"
path = "src/main.rs"

[profile.release]
strip = true
lto = true

[dependencies]
aes-gcm = "0.11.0"
anyhow = "1.0.104"
arboard = "3.6.1"
argon2 = "0.5.3"
base64 = "0.23.1"
mlua = { version = "0.12.0", features = ["lua54", "vendored"] }
portable-pty = "0.9.0"
rand = "0.10.2"
ratatui = "0.30.2"
regex = "1.13.1"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tiny_http = "0.12.0"
tui-term = "0.3.4"
unicode-width = "0.2.2"
ureq = { version = "3.3.0", default-features = false, features = ["rustls", "json"] }
vt100 = "0.16"
zeroize = "1.9.0"
