/* automatically generated by rust-bindgen 0.73.2 */

//! The Rust view of libvpx, generated from its headers and kept here.
//!
//! Generated, because a structure written out by hand is one that can be
//! wrong in a way that corrupts memory rather than failing. Generated ONCE
//! and committed, because generating it needs clang, and this project does
//! not ask anybody to install clang to build it.
//!
//! From libvpx 1.16 headers. A system library of another version is caught
//! at the door: the encoder is opened with the ABI number this was made
//! against, and libvpx refuses a number it does not know rather than
//! reading the wrong bytes.
//!
//! Remade with tools/vpx-bindings.sh.
#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case, dead_code)]

pub const VPX_RC_MAX_STATIC_GF_GROUP_LENGTH: u32 = 250;
pub const VPX_RC_MAX_REF_FRAMES: u32 = 4;
pub const VPX_ENCODER_ABI_VERSION: u32 = 39;
pub const VPX_FRAME_IS_KEY: u32 = 1;
pub const VPX_EFLAG_FORCE_KF: u32 = 1;
pub const VPX_DL_REALTIME: u32 = 1;
pub const vpx_img_fmt_VPX_IMG_FMT_NONE: vpx_img_fmt = 0;
pub const vpx_img_fmt_VPX_IMG_FMT_YV12: vpx_img_fmt = 769;
pub const vpx_img_fmt_VPX_IMG_FMT_I420: vpx_img_fmt = 258;
pub const vpx_img_fmt_VPX_IMG_FMT_I422: vpx_img_fmt = 261;
pub const vpx_img_fmt_VPX_IMG_FMT_I444: vpx_img_fmt = 262;
pub const vpx_img_fmt_VPX_IMG_FMT_I440: vpx_img_fmt = 263;
pub const vpx_img_fmt_VPX_IMG_FMT_NV12: vpx_img_fmt = 265;
pub const vpx_img_fmt_VPX_IMG_FMT_I42016: vpx_img_fmt = 2306;
pub const vpx_img_fmt_VPX_IMG_FMT_I42216: vpx_img_fmt = 2309;
pub const vpx_img_fmt_VPX_IMG_FMT_I44416: vpx_img_fmt = 2310;
pub const vpx_img_fmt_VPX_IMG_FMT_I44016: vpx_img_fmt = 2311;
pub type vpx_img_fmt = ::std::os::raw::c_uint;
pub use self::vpx_img_fmt as vpx_img_fmt_t;
pub const vpx_color_space_VPX_CS_UNKNOWN: vpx_color_space = 0;
pub const vpx_color_space_VPX_CS_BT_601: vpx_color_space = 1;
pub const vpx_color_space_VPX_CS_BT_709: vpx_color_space = 2;
pub const vpx_color_space_VPX_CS_SMPTE_170: vpx_color_space = 3;
pub const vpx_color_space_VPX_CS_SMPTE_240: vpx_color_space = 4;
pub const vpx_color_space_VPX_CS_BT_2020: vpx_color_space = 5;
pub const vpx_color_space_VPX_CS_RESERVED: vpx_color_space = 6;
pub const vpx_color_space_VPX_CS_SRGB: vpx_color_space = 7;
pub type vpx_color_space = ::std::os::raw::c_uint;
pub use self::vpx_color_space as vpx_color_space_t;
pub const vpx_color_range_VPX_CR_STUDIO_RANGE: vpx_color_range = 0;
pub const vpx_color_range_VPX_CR_FULL_RANGE: vpx_color_range = 1;
pub type vpx_color_range = ::std::os::raw::c_uint;
pub use self::vpx_color_range as vpx_color_range_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_image {
    pub fmt: vpx_img_fmt_t,
    pub cs: vpx_color_space_t,
    pub range: vpx_color_range_t,
    pub w: ::std::os::raw::c_uint,
    pub h: ::std::os::raw::c_uint,
    pub bit_depth: ::std::os::raw::c_uint,
    pub d_w: ::std::os::raw::c_uint,
    pub d_h: ::std::os::raw::c_uint,
    pub r_w: ::std::os::raw::c_uint,
    pub r_h: ::std::os::raw::c_uint,
    pub x_chroma_shift: ::std::os::raw::c_uint,
    pub y_chroma_shift: ::std::os::raw::c_uint,
    pub planes: [*mut ::std::os::raw::c_uchar; 4usize],
    pub stride: [::std::os::raw::c_int; 4usize],
    pub bps: ::std::os::raw::c_int,
    pub user_priv: *mut ::std::os::raw::c_void,
    pub img_data: *mut ::std::os::raw::c_uchar,
    pub img_data_owner: ::std::os::raw::c_int,
    pub self_allocd: ::std::os::raw::c_int,
    pub fb_priv: *mut ::std::os::raw::c_void,
}
pub type vpx_image_t = vpx_image;
unsafe extern "C" {
    pub fn vpx_img_wrap(
        img: *mut vpx_image_t,
        fmt: vpx_img_fmt_t,
        d_w: ::std::os::raw::c_uint,
        d_h: ::std::os::raw::c_uint,
        stride_align: ::std::os::raw::c_uint,
        img_data: *mut ::std::os::raw::c_uchar,
    ) -> *mut vpx_image_t;
}
pub const vpx_codec_err_t_VPX_CODEC_OK: vpx_codec_err_t = 0;
pub const vpx_codec_err_t_VPX_CODEC_ERROR: vpx_codec_err_t = 1;
pub const vpx_codec_err_t_VPX_CODEC_MEM_ERROR: vpx_codec_err_t = 2;
pub const vpx_codec_err_t_VPX_CODEC_ABI_MISMATCH: vpx_codec_err_t = 3;
pub const vpx_codec_err_t_VPX_CODEC_INCAPABLE: vpx_codec_err_t = 4;
pub const vpx_codec_err_t_VPX_CODEC_UNSUP_BITSTREAM: vpx_codec_err_t = 5;
pub const vpx_codec_err_t_VPX_CODEC_UNSUP_FEATURE: vpx_codec_err_t = 6;
pub const vpx_codec_err_t_VPX_CODEC_CORRUPT_FRAME: vpx_codec_err_t = 7;
pub const vpx_codec_err_t_VPX_CODEC_INVALID_PARAM: vpx_codec_err_t = 8;
pub const vpx_codec_err_t_VPX_CODEC_LIST_END: vpx_codec_err_t = 9;
pub type vpx_codec_err_t = ::std::os::raw::c_uint;
pub type vpx_codec_flags_t = ::std::os::raw::c_long;
#[repr(C)]
#[derive(Debug)]
pub struct vpx_codec_iface {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug)]
pub struct vpx_codec_priv {
    _unused: [u8; 0],
}
pub type vpx_codec_priv_t = vpx_codec_priv;
pub type vpx_codec_iter_t = *const ::std::os::raw::c_void;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct vpx_codec_ctx {
    pub name: *const ::std::os::raw::c_char,
    pub iface: *const vpx_codec_iface,
    pub err: vpx_codec_err_t,
    pub err_detail: *const ::std::os::raw::c_char,
    pub init_flags: vpx_codec_flags_t,
    pub config: vpx_codec_ctx__bindgen_ty_1,
    pub priv_: *mut vpx_codec_priv_t,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union vpx_codec_ctx__bindgen_ty_1 {
    pub dec: *mut vpx_codec_dec_cfg,
    pub enc: *const vpx_codec_enc_cfg,
    pub raw: *const ::std::os::raw::c_void,
}
pub type vpx_codec_ctx_t = vpx_codec_ctx;
pub const vpx_bit_depth_VPX_BITS_8: vpx_bit_depth = 8;
pub const vpx_bit_depth_VPX_BITS_10: vpx_bit_depth = 10;
pub const vpx_bit_depth_VPX_BITS_12: vpx_bit_depth = 12;
pub type vpx_bit_depth = ::std::os::raw::c_uint;
pub use self::vpx_bit_depth as vpx_bit_depth_t;
unsafe extern "C" {
    pub fn vpx_codec_err_to_string(err: vpx_codec_err_t) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn vpx_codec_error_detail(ctx: *const vpx_codec_ctx_t) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn vpx_codec_destroy(ctx: *mut vpx_codec_ctx_t) -> vpx_codec_err_t;
}
unsafe extern "C" {
    pub fn vpx_codec_control_(
        ctx: *mut vpx_codec_ctx_t,
        ctrl_id: ::std::os::raw::c_int,
        ...
    ) -> vpx_codec_err_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_fixed_buf {
    pub buf: *mut ::std::os::raw::c_void,
    pub sz: usize,
}
pub type vpx_fixed_buf_t = vpx_fixed_buf;
pub type vpx_codec_pts_t = i64;
pub type vpx_codec_frame_flags_t = u32;
pub type vpx_codec_er_flags_t = u32;
pub const vpx_codec_cx_pkt_kind_VPX_CODEC_CX_FRAME_PKT: vpx_codec_cx_pkt_kind = 0;
pub const vpx_codec_cx_pkt_kind_VPX_CODEC_STATS_PKT: vpx_codec_cx_pkt_kind = 1;
pub const vpx_codec_cx_pkt_kind_VPX_CODEC_FPMB_STATS_PKT: vpx_codec_cx_pkt_kind = 2;
pub const vpx_codec_cx_pkt_kind_VPX_CODEC_PSNR_PKT: vpx_codec_cx_pkt_kind = 3;
pub const vpx_codec_cx_pkt_kind_VPX_CODEC_CUSTOM_PKT: vpx_codec_cx_pkt_kind = 256;
pub type vpx_codec_cx_pkt_kind = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct vpx_codec_cx_pkt {
    pub kind: vpx_codec_cx_pkt_kind,
    pub data: vpx_codec_cx_pkt__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union vpx_codec_cx_pkt__bindgen_ty_1 {
    pub frame: vpx_codec_cx_pkt__bindgen_ty_1__bindgen_ty_1,
    pub twopass_stats: vpx_fixed_buf_t,
    pub firstpass_mb_stats: vpx_fixed_buf_t,
    pub psnr: vpx_codec_cx_pkt__bindgen_ty_1_vpx_psnr_pkt,
    pub raw: vpx_fixed_buf_t,
    pub pad: [::std::os::raw::c_char; 124usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_codec_cx_pkt__bindgen_ty_1__bindgen_ty_1 {
    pub buf: *mut ::std::os::raw::c_void,
    pub sz: usize,
    pub pts: vpx_codec_pts_t,
    pub duration: ::std::os::raw::c_ulong,
    pub flags: vpx_codec_frame_flags_t,
    pub partition_id: ::std::os::raw::c_int,
    pub width: [::std::os::raw::c_uint; 5usize],
    pub height: [::std::os::raw::c_uint; 5usize],
    pub spatial_layer_encoded: [u8; 5usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_codec_cx_pkt__bindgen_ty_1_vpx_psnr_pkt {
    pub samples: [::std::os::raw::c_uint; 4usize],
    pub sse: [u64; 4usize],
    pub psnr: [f64; 4usize],
    pub spatial_layer_id: ::std::os::raw::c_int,
}
pub type vpx_codec_cx_pkt_t = vpx_codec_cx_pkt;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_rational {
    pub num: ::std::os::raw::c_int,
    pub den: ::std::os::raw::c_int,
}
pub type vpx_rational_t = vpx_rational;
pub const vpx_enc_pass_VPX_RC_ONE_PASS: vpx_enc_pass = 0;
pub const vpx_enc_pass_VPX_RC_FIRST_PASS: vpx_enc_pass = 1;
pub const vpx_enc_pass_VPX_RC_LAST_PASS: vpx_enc_pass = 2;
pub type vpx_enc_pass = ::std::os::raw::c_uint;
pub const vpx_rc_mode_VPX_VBR: vpx_rc_mode = 0;
pub const vpx_rc_mode_VPX_CBR: vpx_rc_mode = 1;
pub const vpx_rc_mode_VPX_CQ: vpx_rc_mode = 2;
pub const vpx_rc_mode_VPX_Q: vpx_rc_mode = 3;
pub type vpx_rc_mode = ::std::os::raw::c_uint;
pub const vpx_kf_mode_VPX_KF_FIXED: vpx_kf_mode = 0;
pub const vpx_kf_mode_VPX_KF_AUTO: vpx_kf_mode = 1;
pub const vpx_kf_mode_VPX_KF_DISABLED: vpx_kf_mode = 0;
pub type vpx_kf_mode = ::std::os::raw::c_uint;
pub type vpx_enc_frame_flags_t = ::std::os::raw::c_long;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_codec_enc_cfg {
    pub g_usage: ::std::os::raw::c_uint,
    pub g_threads: ::std::os::raw::c_uint,
    pub g_profile: ::std::os::raw::c_uint,
    pub g_w: ::std::os::raw::c_uint,
    pub g_h: ::std::os::raw::c_uint,
    pub g_bit_depth: vpx_bit_depth_t,
    pub g_input_bit_depth: ::std::os::raw::c_uint,
    pub g_timebase: vpx_rational,
    pub g_error_resilient: vpx_codec_er_flags_t,
    pub g_pass: vpx_enc_pass,
    pub g_lag_in_frames: ::std::os::raw::c_uint,
    pub rc_dropframe_thresh: ::std::os::raw::c_uint,
    pub rc_resize_allowed: ::std::os::raw::c_uint,
    pub rc_scaled_width: ::std::os::raw::c_uint,
    pub rc_scaled_height: ::std::os::raw::c_uint,
    pub rc_resize_up_thresh: ::std::os::raw::c_uint,
    pub rc_resize_down_thresh: ::std::os::raw::c_uint,
    pub rc_end_usage: vpx_rc_mode,
    pub rc_twopass_stats_in: vpx_fixed_buf_t,
    pub rc_firstpass_mb_stats_in: vpx_fixed_buf_t,
    pub rc_target_bitrate: ::std::os::raw::c_uint,
    pub rc_min_quantizer: ::std::os::raw::c_uint,
    pub rc_max_quantizer: ::std::os::raw::c_uint,
    pub rc_undershoot_pct: ::std::os::raw::c_uint,
    pub rc_overshoot_pct: ::std::os::raw::c_uint,
    pub rc_buf_sz: ::std::os::raw::c_uint,
    pub rc_buf_initial_sz: ::std::os::raw::c_uint,
    pub rc_buf_optimal_sz: ::std::os::raw::c_uint,
    pub rc_2pass_vbr_bias_pct: ::std::os::raw::c_uint,
    pub rc_2pass_vbr_minsection_pct: ::std::os::raw::c_uint,
    pub rc_2pass_vbr_maxsection_pct: ::std::os::raw::c_uint,
    pub rc_2pass_vbr_corpus_complexity: ::std::os::raw::c_uint,
    pub kf_mode: vpx_kf_mode,
    pub kf_min_dist: ::std::os::raw::c_uint,
    pub kf_max_dist: ::std::os::raw::c_uint,
    pub ss_number_layers: ::std::os::raw::c_uint,
    pub ss_enable_auto_alt_ref: [::std::os::raw::c_int; 5usize],
    pub ss_target_bitrate: [::std::os::raw::c_uint; 5usize],
    pub ts_number_layers: ::std::os::raw::c_uint,
    pub ts_target_bitrate: [::std::os::raw::c_uint; 5usize],
    pub ts_rate_decimator: [::std::os::raw::c_uint; 5usize],
    pub ts_periodicity: ::std::os::raw::c_uint,
    pub ts_layer_id: [::std::os::raw::c_uint; 16usize],
    pub layer_target_bitrate: [::std::os::raw::c_uint; 12usize],
    pub temporal_layering_mode: ::std::os::raw::c_int,
    pub use_vizier_rc_params: ::std::os::raw::c_int,
    pub active_wq_factor: vpx_rational_t,
    pub err_per_mb_factor: vpx_rational_t,
    pub sr_default_decay_limit: vpx_rational_t,
    pub sr_diff_factor: vpx_rational_t,
    pub kf_err_per_mb_factor: vpx_rational_t,
    pub kf_frame_min_boost_factor: vpx_rational_t,
    pub kf_frame_max_boost_first_factor: vpx_rational_t,
    pub kf_frame_max_boost_subs_factor: vpx_rational_t,
    pub kf_max_total_boost_factor: vpx_rational_t,
    pub gf_max_total_boost_factor: vpx_rational_t,
    pub gf_frame_max_boost_factor: vpx_rational_t,
    pub zm_factor: vpx_rational_t,
    pub rd_mult_inter_qp_fac: vpx_rational_t,
    pub rd_mult_arf_qp_fac: vpx_rational_t,
    pub rd_mult_key_qp_fac: vpx_rational_t,
}
pub type vpx_codec_enc_cfg_t = vpx_codec_enc_cfg;
unsafe extern "C" {
    pub fn vpx_codec_enc_init_ver(
        ctx: *mut vpx_codec_ctx_t,
        iface: *const vpx_codec_iface,
        cfg: *const vpx_codec_enc_cfg_t,
        flags: vpx_codec_flags_t,
        ver: ::std::os::raw::c_int,
    ) -> vpx_codec_err_t;
}
unsafe extern "C" {
    pub fn vpx_codec_enc_config_default(
        iface: *const vpx_codec_iface,
        cfg: *mut vpx_codec_enc_cfg_t,
        usage: ::std::os::raw::c_uint,
    ) -> vpx_codec_err_t;
}
pub type vpx_enc_deadline_t = ::std::os::raw::c_ulong;
unsafe extern "C" {
    pub fn vpx_codec_encode(
        ctx: *mut vpx_codec_ctx_t,
        img: *const vpx_image_t,
        pts: vpx_codec_pts_t,
        duration: ::std::os::raw::c_ulong,
        flags: vpx_enc_frame_flags_t,
        deadline: vpx_enc_deadline_t,
    ) -> vpx_codec_err_t;
}
unsafe extern "C" {
    pub fn vpx_codec_get_cx_data(
        ctx: *mut vpx_codec_ctx_t,
        iter: *mut vpx_codec_iter_t,
    ) -> *const vpx_codec_cx_pkt_t;
}
unsafe extern "C" {
    pub fn vpx_codec_vp8_cx() -> *const vpx_codec_iface;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_codec_dec_cfg {
    pub _address: u8,
}
